# Simple workflow for deploying static content to GitHub Pages
name: demo-github-action-html

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
      - name: print pwd
        run: pwd
      - name: Checkout
        uses: actions/checkout@v2

