# Simple workflow for deploying static content to GitHub Pages
name: hello

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

